admin: ""
telegramToken: ""
proxy: ""
plugin:
  ChatGPT:
    key: ""
    base_url: ""
  YamlBuilder:
    hook:
      - validate
    proxy: { }
    # if you don't want to set proxy, please fill in {}
    # http: socks5://127.0.0.1:7891
    # https: socks5://127.0.0.1:7891
    git_proxy: null
    hook_configs:
      search:
        google-play: null
        apple: null